DROP TABLE IF EXISTS events_event_types CASCADE; 

DROP TABLE IF EXISTS registrations CASCADE;

DROP TABLE IF EXISTS event_types CASCADE;

DROP TABLE IF EXISTS events CASCADE;

DROP TABLE IF EXISTS admins CASCADE;